#!/bin/bash -e

CORES=$(grep -c ^processor /proc/cpuinfo)

function test {
	export CC="${1} -Werror"
	export CXX="${2} -Werror"
	make -j $CORES test
	make -j $CORES test DEBUG=1
	make -j $CORES test DEBUG=2

}

(which gcc-4.9 g++-4.9 > /dev/null) && test gcc-4.9 g++-4.9
(which gcc g++ > /dev/null) && test gcc g++
(which clang clang++ > /dev/null) && test clang clang++
