#!/bin/bash
# Args: <archive name> <repositories>...
files=$(for rep in ${@:2}; do
	git -C "$rep" ls-files | sed -e "s@^@$rep/@g"
	for x in $(git -C "$rep" config --file .gitmodules --get-regexp path | awk '{ print $2 }'); do
		git -C "$rep/$x" ls-files | sed -e "s@^@$rep/$x/@g"
	done
done)
# Filter out directories
for file in $files; do
	if [ ! -d "$file" ]; then
		tmp+="$file "
	fi
done
files=$tmp
# Pack files
tar cvzf $1 $files
