#!/bin/bash

DESTDIR=sim/

trap '' SIGINT SIGQUIT SIGTERM

echo "[client]" > .mysql.cnf
chmod 0600 .mysql.cnf
grep 'user\|password' "$DESTDIR/.db.config" | sed 's/: /=/' >> .mysql.cnf
db=$(grep 'db:' "$DESTDIR/.db.config" | sed 's/db: //' | sed 's/^"\|"$//g')
echo $db

echo "Stop SIM"
$DESTDIR/manage stop

echo "Backup database"
mysqldump --defaults-file=.mysql.cnf --result-file=upd_db_sch_backup.sql --extended-insert=FALSE $db || exit 1 # Without backup do nothing!
mysqldump --defaults-file=.mysql.cnf --result-file=upd_db_sch.sql --complete-insert -t $db || exit 1

echo "Update Schemas"
build/setup-installation --drop-tables "$DESTDIR"

echo "Fill with data"
echo "DELETE FROM users;" | mysql --defaults-file=.mysql.cnf $db # Remove just created root account
mysql --defaults-file=.mysql.cnf $db < upd_db_sch.sql || mysql --defaults-file=.mysql.cnf $db < upd_db_sch_backup.sql

echo "Restore SIM"
$DESTDIR/manage -b start

echo "Save backup"
for ((i=0;;++i)); do
	if [ ! -f "${db}-backup.${i}" ]; then
		mv upd_db_sch_backup.sql "${db}-backup.${i}"
		break
	fi
done

echo "Cleaning"
rm upd_db_sch.sql
rm .mysql.cnf
