export

SHELL = /bin/sh

# Clear default rules
.SUFFIXES:

# Extra options to compile project with
EXTRA_OPTIONS = -O3

# Extra options to link project with
EXTRA_LD_OPTIONS = $(EXTRA_OPTIONS)

# Warning options to compile project with
WARNING_OPTIONS = -Wall -Wextra -Wshadow -Wfloat-equal -Wno-unused-result # -Weffc++

CFLAGS = $(WARNING_OPTIONS) $(EXTRA_OPTIONS)
CXXFLAGS = $(CFLAGS) -std=c++11
LFLAGS = $(EXTRA_LD_OPTIONS)

# Shell commands
MV = mv -f
CP = cp -rf
UPDATE = $(CP) -u
RM = rm -f
MKDIR = mkdir -p

DEBUG = 0
VERBOSE = 0

ifeq ($(DEBUG), 1)
CFLAGS += -DDEBUG
else ifeq ($(DEBUG), 2)
CFLAGS += -g -O0
LFLAGS += -g -O0
else ifeq ($(DEBUG), 3)
CFLAGS += -DDEBUG -g -O0
LFLAGS += -g -O0
endif

# Rest
ifeq ($(MAKELEVEL), 0)
ROOT := $(shell pwd)
ifneq ($(shell printf $(ROOT) | tail -c 1), $(shell printf "/"))
ROOT := $(ROOT)/
endif
endif

ifeq ($(VERBOSE),1)
	Q :=
	P =
else
	Q := @
	P = @printf "  %-8s %s\n" '$(1)' '$(subst $(ROOT),,$(abspath $(2)))';
	MAKEFLAGS += --no-print-directory
	# If CMDGOAL is not one of these: install, reinstall, uninstall
	ifeq (,$(filter $(MAKECMDGOALS), install reinstall uninstall))
		MAKEFLAGS += -s
	endif
endif

# Default rules
%.o: %.c
	$(Q)$(call P,CC,$@)$(CC) $< $(CFLAGS) -c -o $@

%.o: %.cc
	$(Q)$(call P,CXX,$@)$(CXX) $< $(CXXFLAGS) -c -o $@

%.o: %.cpp
	$(Q)$(call P,CXX,$@)$(CXX) $< $(CXXFLAGS) -c -o $@

%.c.deps: %.c
	$(Q) echo -n "$@ " > $@
	$(Q)$(call P,CC,$@)$(CC) -MM $(CFLAGS) $< >> $@ || { $(RM) $@; exit 1; }

%.cc.deps: %.cc
	$(Q) echo -n "$@ " > $@
	$(Q)$(call P,CXX,$@)$(CXX) -MM $(CXXFLAGS) $< >> $@ || { $(RM) $@; exit 1; }

%.cpp.deps: %.cpp
	$(Q) echo -n "$@ " > $@
	$(Q)$(call P,CXX,$@)$(CXX) -MM $(CXXFLAGS) $< >> $@ || { $(RM) $@; exit 1; }

.PHONY: FORCE
FORCE:

.DEFAULT_GOAL :=
