#!/bin/bash -e

CORES=$(grep -c ^processor /proc/cpuinfo)

export CC='gcc -Werror'
export CXX='g++ -Werror'
make build test -j $CORES test
make build test -j $CORES test DEBUG=1
make build test -j $CORES test DEBUG=2

export CC='clang -Werror'
export CXX='clang++ -Werror'
make build test -j $CORES test
make build test -j $CORES test DEBUG=1
make build test -j $CORES test DEBUG=2
