#!/bin/sh

DESTDIR=build

trap '' SIGINT SIGQUIT SIGTERM

echo "[client]" > .mysql.cnf
chmod 0600 .mysql.cnf
grep 'user\|password' "$DESTDIR/.db.config" | sed 's/: /=/' >> .mysql.cnf
db=$(grep 'db:' "$DESTDIR/.db.config" | sed 's/db: //')
echo $db

echo "Stop SIM"
src/killinstc --wait $DESTDIR/sim-server
src/killinstc --wait $DESTDIR/job-server

echo "Backup database"
mysqldump --defaults-file=.mysql.cnf --result-file=upd_db_sch_backup.sql --extended-insert=FALSE $db
mysqldump --defaults-file=.mysql.cnf --result-file=upd_db_sch.sql --complete-insert -t $db

echo "Update Schemas"
src/setup-installation "$DESTDIR" --drop-tables

echo "Fill with data"
echo "TRUNCATE TABLE users;" | mysql --defaults-file=.mysql.cnf $db
mysql --defaults-file=.mysql.cnf $db < upd_db_sch.sql || mysql --defaults-file=.mysql.cnf $db < upd_db_sch_backup.sql

echo "Restore SIM"
make run DESTDIR="$DESTDIR"

echo "Save backup"
for ((i=0;;++i)); do
	if [ ! -f "${db}-backup.${i}" ]; then
		mv upd_db_sch_backup.sql "${db}-backup.${i}"
		break
	fi
done

echo "Cleaning"
rm upd_db_sch.sql
rm .mysql.cnf
